version: "3.9"
services:
  cloudflare-ddns:
    build: .
    container_name: cloudflare-ddns
    volumes: 
      - /Users/helieting/containers/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
